name: ExpTech_Economy
version: 1.2
author: whes1015
main: main.main
api-version: 1.18

commands:
  ec:
    description: 控制 ExpTech_Economy 插件
    usage: /ec <args>
    permission: exptech.admin